X:  [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
0, 0, 0, Variable((), boolean=True), 0, 0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0
0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0
0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0
0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0
0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0
0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0
0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, Variable((), boolean=True), 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0
0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0
0, 0, 0, 0, 0, 0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, 0, Variable((), boolean=True), Expression(UNKNOWN, NONNEGATIVE, ()), 0
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0
0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, Variable((), boolean=True), 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0
0, 0, 0, 0, 0, 0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0
0, 0, 0, 0, 0, 0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, 0, Expression(UNKNOWN, NONNEGATIVE, ()), 0, 0, 0, Expression(QUASICONCAVE, NONNEGATIVE, ()), Expression(UNKNOWN, NONNEGATIVE, ()), 0]]

